#!/bin/sh
#
# This is a script to easily launch discline
# from an application launcher or similar.
#
# http://github.com/mitchweaver/Discline
#
# These are just examples of what I use,
# edit them to match your system and needs.

term='st'
font='MonteCarlo'
shell='/bin/dash'
DISCLINE_DIR="${HOME}/workspace/Discline"
PYTHON_VERSION='3.6'

# ------------------------------------------------------- 

$term -f $font -e $shell -c "cd $DISCLINE_DIR  && \
    python$PYTHON_VERSION Discline.py" &
